/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AzureSafetyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAuthorizedAdmin"
      | "aggregateScores"
      | "applyPenalty"
      | "assignUserToSegment"
      | "checkThreshold"
      | "getAuthorizedAdmins"
      | "getCurrentScore"
      | "getEvent"
      | "getGlobalThreshold"
      | "getSegmentScore"
      | "getSegmentThreshold"
      | "getUserEventIds"
      | "getUserSegmentId"
      | "isAuthorizedAdmin"
      | "protocolId"
      | "removeAuthorizedAdmin"
      | "reportEvent"
      | "setGlobalThreshold"
      | "setSegmentThreshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminRemoved"
      | "AggregateCalculated"
      | "EventReported"
      | "PenaltyApplied"
      | "ScoreUpdated"
      | "ThresholdSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAuthorizedAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aggregateScores",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "applyPenalty",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignUserToSegment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkThreshold",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorizedAdmins",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSegmentScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSegmentThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEventIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSegmentId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportEvent",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalThreshold",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSegmentThreshold",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAuthorizedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aggregateScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignUserToSegment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorizedAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSegmentScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSegmentThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEventIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSegmentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSegmentThreshold",
    data: BytesLike
  ): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [admin: AddressLike];
  export type OutputTuple = [admin: string];
  export interface OutputObject {
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [admin: AddressLike];
  export type OutputTuple = [admin: string];
  export interface OutputObject {
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AggregateCalculatedEvent {
  export type InputTuple = [
    caller: AddressLike,
    aggregateHandle: BytesLike,
    segmentIds: BigNumberish[]
  ];
  export type OutputTuple = [
    caller: string,
    aggregateHandle: string,
    segmentIds: bigint[]
  ];
  export interface OutputObject {
    caller: string;
    aggregateHandle: string;
    segmentIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventReportedEvent {
  export type InputTuple = [
    reporter: AddressLike,
    eventId: BigNumberish,
    eventType: BigNumberish
  ];
  export type OutputTuple = [
    reporter: string,
    eventId: bigint,
    eventType: bigint
  ];
  export interface OutputObject {
    reporter: string;
    eventId: bigint;
    eventType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PenaltyAppliedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [user: AddressLike, eventId: BigNumberish];
  export type OutputTuple = [user: string, eventId: bigint];
  export interface OutputObject {
    user: string;
    eventId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdSetEvent {
  export type InputTuple = [segmentId: BigNumberish, isGlobal: boolean];
  export type OutputTuple = [segmentId: bigint, isGlobal: boolean];
  export interface OutputObject {
    segmentId: bigint;
    isGlobal: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AzureSafety extends BaseContract {
  connect(runner?: ContractRunner | null): AzureSafety;
  waitForDeployment(): Promise<this>;

  interface: AzureSafetyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAuthorizedAdmin: TypedContractMethod<
    [admin: AddressLike],
    [void],
    "nonpayable"
  >;

  aggregateScores: TypedContractMethod<
    [segmentIds: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  applyPenalty: TypedContractMethod<
    [user: AddressLike, encryptedPenalty: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  assignUserToSegment: TypedContractMethod<
    [user: AddressLike, segmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkThreshold: TypedContractMethod<
    [user: AddressLike, useGlobal: boolean],
    [string],
    "nonpayable"
  >;

  getAuthorizedAdmins: TypedContractMethod<[], [string[]], "view">;

  getCurrentScore: TypedContractMethod<[user: AddressLike], [string], "view">;

  getEvent: TypedContractMethod<
    [eventId: BigNumberish],
    [
      [bigint, string, bigint, string] & {
        eventType: bigint;
        scoreChange: string;
        timestamp: bigint;
        reporter: string;
      }
    ],
    "view"
  >;

  getGlobalThreshold: TypedContractMethod<[], [string], "view">;

  getSegmentScore: TypedContractMethod<
    [segmentId: BigNumberish],
    [string],
    "view"
  >;

  getSegmentThreshold: TypedContractMethod<
    [segmentId: BigNumberish],
    [string],
    "view"
  >;

  getUserEventIds: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getUserSegmentId: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  isAuthorizedAdmin: TypedContractMethod<
    [admin: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removeAuthorizedAdmin: TypedContractMethod<
    [admin: AddressLike],
    [void],
    "nonpayable"
  >;

  reportEvent: TypedContractMethod<
    [
      eventType: BigNumberish,
      encryptedScoreChange: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  setGlobalThreshold: TypedContractMethod<
    [encryptedThreshold: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  setSegmentThreshold: TypedContractMethod<
    [
      segmentId: BigNumberish,
      encryptedThreshold: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAuthorizedAdmin"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "aggregateScores"
  ): TypedContractMethod<[segmentIds: BigNumberish[]], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "applyPenalty"
  ): TypedContractMethod<
    [user: AddressLike, encryptedPenalty: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignUserToSegment"
  ): TypedContractMethod<
    [user: AddressLike, segmentId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkThreshold"
  ): TypedContractMethod<
    [user: AddressLike, useGlobal: boolean],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuthorizedAdmins"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCurrentScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [eventId: BigNumberish],
    [
      [bigint, string, bigint, string] & {
        eventType: bigint;
        scoreChange: string;
        timestamp: bigint;
        reporter: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGlobalThreshold"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSegmentScore"
  ): TypedContractMethod<[segmentId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getSegmentThreshold"
  ): TypedContractMethod<[segmentId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getUserEventIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserSegmentId"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedAdmin"
  ): TypedContractMethod<[admin: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeAuthorizedAdmin"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportEvent"
  ): TypedContractMethod<
    [
      eventType: BigNumberish,
      encryptedScoreChange: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGlobalThreshold"
  ): TypedContractMethod<
    [encryptedThreshold: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSegmentThreshold"
  ): TypedContractMethod<
    [
      segmentId: BigNumberish,
      encryptedThreshold: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "AggregateCalculated"
  ): TypedContractEvent<
    AggregateCalculatedEvent.InputTuple,
    AggregateCalculatedEvent.OutputTuple,
    AggregateCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "EventReported"
  ): TypedContractEvent<
    EventReportedEvent.InputTuple,
    EventReportedEvent.OutputTuple,
    EventReportedEvent.OutputObject
  >;
  getEvent(
    key: "PenaltyApplied"
  ): TypedContractEvent<
    PenaltyAppliedEvent.InputTuple,
    PenaltyAppliedEvent.OutputTuple,
    PenaltyAppliedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdSet"
  ): TypedContractEvent<
    ThresholdSetEvent.InputTuple,
    ThresholdSetEvent.OutputTuple,
    ThresholdSetEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminRemoved(address)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "AggregateCalculated(address,bytes32,uint256[])": TypedContractEvent<
      AggregateCalculatedEvent.InputTuple,
      AggregateCalculatedEvent.OutputTuple,
      AggregateCalculatedEvent.OutputObject
    >;
    AggregateCalculated: TypedContractEvent<
      AggregateCalculatedEvent.InputTuple,
      AggregateCalculatedEvent.OutputTuple,
      AggregateCalculatedEvent.OutputObject
    >;

    "EventReported(address,uint256,uint8)": TypedContractEvent<
      EventReportedEvent.InputTuple,
      EventReportedEvent.OutputTuple,
      EventReportedEvent.OutputObject
    >;
    EventReported: TypedContractEvent<
      EventReportedEvent.InputTuple,
      EventReportedEvent.OutputTuple,
      EventReportedEvent.OutputObject
    >;

    "PenaltyApplied(address,uint256)": TypedContractEvent<
      PenaltyAppliedEvent.InputTuple,
      PenaltyAppliedEvent.OutputTuple,
      PenaltyAppliedEvent.OutputObject
    >;
    PenaltyApplied: TypedContractEvent<
      PenaltyAppliedEvent.InputTuple,
      PenaltyAppliedEvent.OutputTuple,
      PenaltyAppliedEvent.OutputObject
    >;

    "ScoreUpdated(address,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;

    "ThresholdSet(uint256,bool)": TypedContractEvent<
      ThresholdSetEvent.InputTuple,
      ThresholdSetEvent.OutputTuple,
      ThresholdSetEvent.OutputObject
    >;
    ThresholdSet: TypedContractEvent<
      ThresholdSetEvent.InputTuple,
      ThresholdSetEvent.OutputTuple,
      ThresholdSetEvent.OutputObject
    >;
  };
}
